[workspace]
resolver = '2'
members = ['daemon', 'client', "shared"]

[workspace.package]
authors = [ "Sabrina Andersen <NukingDragons>" ]
license = "MIT"
version = "1.0.0"

[profile.release]
panic = "abort"
